import Head from 'next/head'
import React from 'react'
import styles from '../styles/About.module.css'
const About = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.center}>About Hunting Coder</h1>
            <h2> Introduction</h2>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam deleniti necessitatibus qui aperiam repudiandae nulla quo, natus aspernatur ipsum quod doloribus sapiente atque harum temporibus officiis quaerat dolorem maxime quos. Fugiat dolorum animi id suscipit iusto. Explicabo unde expedita, porro dolores perferendis, obcaecati nisi at quae quo quasi neque fuga! Quo rem earum ducimus magni quibusdam, fugiat ipsa a laboriosam minima! Possimus magni quia sit quidem perferendis maxime, ipsa quasi suscipit accusantium dicta in, unde voluptas vel cumque facilis impedit nesciunt voluptate, iure consectetur. Vitae voluptatibus obcaecati ea, pariatur alias reprehenderit ut tempore sunt eveniet dolorum id culpa ex quidem?</p>
            <p>We offer following serivces</p>
            <ul>
                <li>Service 1</li>
                <li>Service 2</li>
                <li>Service 3</li>
                <li>Service 4</li>
                <li>Service 5</li>
            </ul>
            <h2>Services Offered</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illum cum dignissimos laboriosam atque mollitia suscipit ipsum ad tempore architecto nisi repellendus aut, asperiores consectetur quod magnam omnis nostrum? Unde recusandae, ipsum nulla harum possimus illum! Ipsum maiores repellat repudiandae. Culpa expedita rem alias repellendus ea fugit! Neque perspiciatis aut iste!</p>
            <h2>Contact Us</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore ipsa, nesciunt praesentium quia ducimus aspernatur placeat odit architecto sequi eligendi.</p>
        </div>
    )
}

export default About