import Head from 'next/head'
import React, { useState } from 'react';
import styles from '../styles/Blog.module.css'
import Link from 'next/link';
import * as fs from 'fs';

// Step 1: Collect all the files from blogdata directory
// Step 2: Iterate through them and Display them

const Blog = (props) => {
    const [blogs, setBlogs] = useState(props.allBlogs);
    // useEffect(() => {

    // }, [])
    return <div className={styles.container}>
        <Head>
            <title>Our Blogs</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            {blogs.map((blogitem) => {
                return <div key={blogitem.slug}>
                    <Link href={`/blogpost/${blogitem.slug}`}>
                        <h3 className={styles.blogItemh3}>{blogitem.title}</h3></Link>
                    {/* if the metadesc has more than 15 words then displau the first 15 words and ... else display the words */}
                    <p className={styles.blogItemp}>{blogitem.metadesc.split(" ").length > 15 ? blogitem.metadesc.split(" ").slice(0, 15).join(" ") + "..." : blogitem.metadesc}</p>
                    <Link href={`/blogpost/${blogitem.slug}`}><button className={styles.btn}>Read More</button></Link>
                </div>
            })}
        </main>
    </div>
};


export async function getStaticProps(context) {
    let data = await fs.promises.readdir("blogdata");
    let myfile;
    let allBlogs = [];
    for (let index = 0; index < data.length; index++) {
        const item = data[index];
        // console.log(item)
        myfile = await fs.promises.readFile(('blogdata/' + item), 'utf-8')
        allBlogs.push(JSON.parse(myfile))
    }

    return {
        props: { allBlogs }, // will be passed to the page component as props
    }
}

export default Blog;